version: "2"
services: 
  neo4j:
    restart: always
    image: neo4j:latest
    ports:
      - "17474:7474"
  postgresql:
    restart: always
    image: postgres:latest 
    environment:
      - DEBUG=true
      - DB_USER=docker
      - DB_PASS=docker
    ports:
      - "5432:5432"



